TP_1_PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import status_page.urls as status_page
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
import dashboardNavbarFooter.urls as dashboard
import add_friend.urls as add_friend
import profile_page.urls as profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^add_friend/', include(add_friend,namespace='add_friend')),
    url(r'^dashboard/', include(dashboard,namespace='dashboard')),
    url(r'^profile/', include(profile,namespace='profile')),
    url(r'^status-page/', include(status_page, namespace='status-page')),
    url(r'^$', RedirectView.as_view(url='/status-page/', permanent='True'),name='index'),
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
 ]

dashboardNavbarFooter/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
 ]

profile_page/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
 ]

status_page/urls.py
from django.conf.urls import url
from .views import index, status_post

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^status_post', status_post, name='status_post'),
]

add_friend/models.py
from django.db import models

class Friends(models.Model):
	
	name 	= models.CharField(max_length=30)
	url		= models.URLField()
	created_date = models.DateTimeField(auto_now_add=True)

dashboardNavbarFooter/models.py
from django.db import models

# Create your models here.

profile_page/models.py
from django.db import models

# Create your models here.

status_page/models.py
from django.db import models

class Status(models.Model):
    status_content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

status_page/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid' : 'Isi input dengan email',
    }
    attrs = {
        'type' : 'text',
        'class': 'status-form-textarea',
        'placeholder' : 'Update status here',
    }

    status_content = forms.CharField(label='', widget=forms.Textarea(attrs=attrs), required=True)

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms_add import Forms_add
from .models import Friends
from urllib.request import urlopen
from urllib.error import URLError
from dashboardNavbarFooter.views import author


# Create your views here.
response = {'author':author}
def index(request):
	friend = Friends.objects.all()
	response['friend'] = friend
	html = 'add_friend.html'
	response['forms_add'] = Forms_add
	return render(request, html, response)

def add_friend(request):
	form = Forms_add(request.POST or None)
	if(request.method == 'POST' and form.is_valid() and url_is_valid(request.POST['url'])):
		response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
		response['url'] = request.POST['url']
		friends = Friends(name=response['name'], url=response['url'])
		friends.save()
		return HttpResponseRedirect('/add_friend/')
	else:        
		return HttpResponseRedirect('/add_friend/')

def url_is_valid(url):
    try:
        thepage = urlopen(url)
    except URLError as e:
        return False
    else:
        return True

dashboardNavbarFooter/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from status_page.models import Status
from add_friend.models import Friends
from profile_page.views import nama_profile

author = 'Fadhlan Hazmi, Indra Septama, Jovanta Anugerah, Naomi Riana'
def index(request):
	response = {'author': author}
	response['contentss']=''
	response['created_date']=''
	if (Status.objects.all().count() > 0):
		feed = Status.objects.all().order_by('-created_date')[0]
		response['contentss'] = feed.status_content
		response['created_date'] = feed.created_date
	response['friends'] = Friends.objects.all().count()
	response['feeds'] = Status.objects.all().count()
	response['nama'] = nama_profile
	html = 'dashboard.html'
	return render(request, html, response)

profile_page/views.py
from django.shortcuts import render
response = {'author': 'Fadhlan Hazmi, Indra Septama, Jovanta Anugerah, Naomi Riana'}
nama_profile= 'alex Jahmer'
birth_profile = '12/02/1998'
gender_profile = 'male'
bio_profile = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum'
email_profile = 'email@mail.com'
# Create your views here.
def index(request):
    response['name'] = nama_profile
    response['birth'] = birth_profile
    response['gender'] = gender_profile
    response['description'] = bio_profile
    response['email'] = email_profile
    html = 'profile.html'

    return render(request, html,response)

status_page/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import  Status_Form
from .models import  Status

# Create your views here.
response = {}
def index(request):
    response['author'] ='Nao'
    response['status_form'] = Status_Form
    response['all_status'] = Status.objects.all().order_by('created_date').reverse()
    html = 'status_page/status_page.html'
    return  render(request, html, response )

def status_post(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST'):
        response['status_content'] = request.POST['status_content']
        status_jadi = Status(status_content=response['status_content'])
        status_jadi.save()
        return  HttpResponseRedirect('/status-page/')
    else:
        return  HttpResponseRedirect('/status-page/')

add_friend/templates/add_friend.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link type ="text/css" href="{% static 'css/add_friend.css' %}" rel="stylesheet">
<section name='add-input' id='add-input'>
	<h4>Add Friend</h4>
	<form id='form' method="POST" action="{% url 'add_friend:add_friend' %}">
		{% csrf_token %}
        {{ forms_add }}
        <br>
	    <button id="submit" type="submit" class="btn pull-right btn-primary">Add Friend</button>
	</form>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <div class="flex">
            {% if friend %}
                {% for data in friend %}
                    <div class="flex-item">
                        <div class="friends-list">
                            <div class="friend-list-image">
                                <img id="friend-image" src="http://keuda.kemendagri.go.id/asset/dataupload/profil-direktorat/320004365.png" alt="profile-image"/>
                            </div>
                            <div class="friend-list-name">
                                {{data.name}}
                            </div>
                            <div class="friend-list-url">
                                <a href="{{ data.url }}" target="_blank">{{ data.url }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</section>
<section name='friend-list' id='friend-list'>
	<h4>List Friend</h4>
	<table class='table table-responsive table-hover'>
		<tbody>
			{% if friend %}
				{% for i in friend %}
				<tr>
					<td> {{ i.name }} </td>
					<td></td>
					<td> <a href="{{ i.url }}" target="_blank">{{ i.url }}</a> </td>
					<td><i> Added 	{{ i.created_date }} </i></td>
				</tr>
				{% endfor %}
			{% else %}
			<div class="alert alert-danger text-center">
                <strong>Oops!</strong> You don't have any friends.
            </div>
            {% endif %}
		</tbody>
	</table>
</section>
{% endblock %}

dashboardNavbarFooter/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
<style type="text/css">
	body{
		color:lightgrey;
	}
	.image{
		border-radius:90%;
		width:150px;
		height:150px;
		margin-left: 43%;
	}
	.image2{
		border-radius:90%;
		width:80px;
		height:80px;
	}
	.navbar-brand,ul{
		font-size:20px;
	}
	p{
		font-size: 18px
	}
	h1{
		font-size:23px;
		display: inline-block;
		font-weight: bold;
		margin-left: 28%;
	}
	h2{
		font-size:32px;
	}
	h3{
		font-size:38px;
		display: inline-block;
		margin-left: 10%
		font-weight: bold;
	}
	h4{
		font-size:25px;
	}
	h5{
		font-size: 22px;
		display: inline-block;
		margin-left: 15px;
	}
	h6{
		font-size: 13px;
	}
	#name{
		font-size:38px;
		text-align: center;
		margin-left: 10%
		font-weight: bold;
	}
	#feeds{
		margin-left: 12%;
	}
	.content{
		width: 250px;
	}
</style>

<h4>Statistic</h4>
<img alt="Fadhlan Hazim" class="image" src="https://lh3.googleusercontent.com/ez8pDFoxU2ZqDmyfeIjIba6dWisd8MY_6choHhZNpO0WwLhICu0v0s5eV2WHOhuhKw=w170">
<p id = "name">{{nama}}</p>
<br></br>

<h1>Friends</h1>
<h5>{{friends}} People</h5>
<h1 id="feeds">Feeds</h1>
<h5>{{feeds}} Posts</h5>
</br>
</br>
<hr></hr>

<h2>Latest Post</h2>
<img alt="Fadhlan Hazim" class="image2" src="https://lh3.googleusercontent.com/ez8pDFoxU2ZqDmyfeIjIba6dWisd8MY_6choHhZNpO0WwLhICu0v0s5eV2WHOhuhKw=w170">
<h3 style="font-size: 25px">{{nama}}</h3>
</br>
<div class="content">
  <p>{{ contentss }}</p>
  <h6>{{ created_date }}</h6>
</div>

{% endblock %}

profile_page/templates/profile.html
{% extends "base.html" %}
{% block content %}

    <style media="screen">
      button{
        padding: 10px;

      }
      p,h1,h2,h3,h4{

      }
      body{
        background-color: #f3f3f3;
      }
	  .col-sm-12{
		background-color: #f5f3f3;
	  }
    .btn{
      color: black;
    }
	  header{
      font-size: 25px;
    }
    </style>
  <body>
    <h1>Profile</h1>
  <div class="bio">
    <div class="row">
        <img src="https://lh3.googleusercontent.com/ez8pDFoxU2ZqDmyfeIjIba6dWisd8MY_6choHhZNpO0WwLhICu0v0s5eV2WHOhuhKw=w170" alt="">
        <strong><h3>{{name}}</h3>
        <p>Birthday       {{birth}}</p>
        <p>Gender         {{gender}}</p>
        <p>Expertise <button type="button" class="btn btn-outline-secondary">Charismatic</button><button type="button" class="btn btn-outline-secondary">Good Looking</button><button type="button" class="btn btn-outline-secondary">Fast Learner</button></p>
        <p>Description    {{description}}</p>
        <p>Email          {{email}}</p></strong>
</div>
</div>
{% endblock %}

status_page/templates/status_page.html
{% extends 'base.html' %}
{% block content %}
    <meta charset="UTF-8">
    <title>Status Page</title>
<style>


    .status-box .name-box h5{
            font-size: 16px;
            font-weight: bold;
            color: #141823;
            margin: 0;
            padding: 0;
    }

    hr {
          line-height: 1px;
          height: 1px;
          color: rgba(0, 0, 0, .1);
          background: rgba(0, 0, 0, .1);
          border: 0;
    }

    #input-status #form  h3 {
        font-family: Montserrat;
        font-weight: bold;
        font-size: 24px;
    }

    #input-status #form> .status-form-textarea{
        box-sizing: border-box;
        height:  50%;
        font-family: "Open Sans", "helvetica", "Arial";
        font-size: 14px;
        width: 100%;
    }

    #input-status .btn btn-lg btn-block btn-info{
        width: 20px;
    }

    .status-box{
        background-color: white;
    }

    .status-box .content {
        padding: 12px;
    }

    .status-box  .status-box-header {
      max-height: 40px;
      margin-bottom: 11px;
    }

    .status-box .status-box-header .profile-pic-box{
          float: left;
          width: 40px;
          height: 40px;
          margin-right: 8px;
    }

    .status-box .status-box-header .profile-pic{
        border-radius: 50%;
        height: 40px;
        width: 40px;
    }

    .status-box .status-box-header .name-box{
        width: calc(100% - 40px - 8px);
    }


    .status-box .content .status-content-box{
        padding-left: 48px;
    }

    .status-box  .comment-section{
        border-top: 1px solid #e1e2e3;
        margin: 0;
        padding: 9px 12px 7px 12px;
        font-size: 12px;
        background-color: #f6f7f8;
        border-radius: 0 0 3px 3px;
        color: #141823;
        overflow: hidden;
    }

    .status-box .comment-section .row{
        width: 32px;
        height: 50px;
        float: left;
        margin-right: 8px;
    }

    .status-box .comment-section .write-comment input[type="text"]{
        margin-left: 50%;
        max-width: 3000%;
        min-width: 2000%
    }

    #submit{
        width:100px;
        font-size:90%;
    }


</style>
<body>
    <section name="input-status" id="input-status">
        <div class="container">
            <form id="form" method="POST" action="{% url 'status-page:status_post' %}">
                <h3>Update Status</h3>
                {% csrf_token %}
                {{ status_form}}
                <br>
                <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            </form>
        </div>
    </section>
    <br>
<section name="all-status" id="all-status">
<div class="container">

    {% for status  in all_status %}
        <div class="status-box">
            <div class="content">
                <div class="status-box-header">
                    <div class="profile-pic-box">
                        <img class="profile-pic" src="https://68.media.tumblr.com/9103b7aa4ce37f5995f64cc1705a3683/tumblr_njydxvU2IZ1sf8yjgo3_400.gif" alt="">
                    </div>
                    <div class="name-box">
                        <h5>Chiyoko</h5>
                        <span class="status-date-added">{{ status.created_date }}</span>
                    </div>
                </div>
                <div class="status-content-box">
                    {{ status.status_content }}
                </div>
                <hr />
            </div>
    </div>
        <br>
    {% endfor %}
</div>

</section>
</body>
{% endblock %}

status_page/templates/status_page/partials/header.html
<!-- Fixed navbar -->
<style type="text/css">
    .bg-navbar{
        background-color: #71b5ff
    }

    .navbar-header .navbar-brand{
        font-weight: bold;
        color: #f9ffed;
        font-family: Montserrat;
        font-size: 24px;
    }
    .navbar-collapse .nav{
        font-weight: bold;
        color: #f9ffed;
        font-family: Montserrat;
        font-size: 18px;
    }

    .navbar-right{
        margin-right: 100px;
        font-weight: bold;
        color: #f9ffed;
        font-family: Montserrat;
        font-size: 18px;
    }

</style>
<div class="container-fullwidth">
  <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-navbar navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" >LING ON</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="#"> Add Friend </a></li>
        <li><a href="#"> Status </a> </li>
        <li><a href="#"> Profile </a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </nav>
</div>

status_page/templates/status_page/status_page.html
{% extends 'base.html' %}
{% block content %}
    <meta charset="UTF-8">
    <title>Status Page</title>

<style>
    body {
        background: #E9EAED;
        font-family: helvetica, arial, sans-serif;
        color: #141823;
        font-size: 14px;
        line-height: 1.38;
    }

    .status-box .name-box h5{
            font-size: 16px;
            font-weight: bold;
            color: #141823;
            margin: 0;
            padding: 0;
    }

    hr {
          line-height: 1px;
          height: 1px;
          color: rgba(0, 0, 0, .1);
          background: rgba(0, 0, 0, .1);
          border: 0;
    }

    #input-status #form  h3 {
        font-family: Montserrat;
        font-weight: bold;
        font-size: 24px;
    }

    #input-status #form> .status-form-textarea{
        box-sizing: border-box;
        height:  50%;
        font-family: "Open Sans", "helvetica", "Arial";
        font-size: 14px;
        width: 100%;
    }

    #input-status .btn btn-lg btn-block btn-info{
        width: 20px;
    }

    .status-box{
        background-color: white;
    }

    .status-box .content {
        padding: 12px;
    }

    .status-box  .status-box-header {
      max-height: 40px;
      margin-bottom: 11px;
    }

    .status-box .status-box-header .profile-pic-box{
          float: left;
          width: 40px;
          height: 40px;
          margin-right: 8px;
    }

    .status-box .status-box-header .profile-pic{
        border-radius: 50%;
        height: 40px;
        width: 40px;
    }

    .status-box .status-box-header .name-box{
        width: calc(100% - 40px - 8px);
    }


    .status-box .content .status-content-box{
        padding-left: 48px;
    }

    .status-box  .comment-section{
        border-top: 1px solid #e1e2e3;
        margin: 0;
        padding: 9px 12px 7px 12px;
        font-size: 12px;
        background-color: #f6f7f8;
        border-radius: 0 0 3px 3px;
        color: #141823;
        overflow: hidden;
    }

    .status-box .comment-section .row{
        width: 32px;
        height: 50px;
        float: left;
        margin-right: 8px;
    }

    .status-box .comment-section .write-comment input[type="text"]{
        margin-left: 50%;
        max-width: 3000%;
        min-width: 2000%
    }

    #submit{
        width:100px;
        font-size:90%;
    }


</style>
<body>
    <section name="input-status" id="input-status">
        <div class="container">
            <form id="form" method="POST" action="{% url 'status-page:status_post' %}">
                <h3>Update Status</h3>
                {% csrf_token %}
                {{ status_form}}
                <br>
                <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            </form>
        </div>
    </section>
    <br>
<section name="all-status" id="all-status">
<div class="container">

    {% for status  in all_status %}
        <div class="status-box">
            <div class="content">
                <div class="status-box-header">
                    <div class="profile-pic-box">
                        <img class="profile-pic" src="https://lh3.googleusercontent.com/ez8pDFoxU2ZqDmyfeIjIba6dWisd8MY_6choHhZNpO0WwLhICu0v0s5eV2WHOhuhKw=w170" alt="">
                    </div>
                    <div class="name-box">
                        <h5>Fadhlan Hazmi</h5>
                        <span class="status-date-added">{{ status.created_date }}</span>
                    </div>
                </div>
                <div class="status-content-box">
                    {{ status.status_content }}
                </div>
                <hr />
            </div>
    </div>
        <br>
    {% endfor %}
</div>

</section>
</body>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <title> 
        {% block title %} Tugas 1 By {{author}}{% endblock %}
    </title>
    <style type="text/css">
    body{
        background: linear-gradient(#0f0c29,#302b63);
        width:auto;
        color: lightgrey;
    }
    p{
        font-family: 'Roboto', sans-serif;
    }
    .navbar-brand,ul{
        font-size:20px;
    }
    h1,h2,h3,h4,h5,h6{
        font-family: 'Roboto', sans-serif;
    }

</style>
</head>

<body>
    <header>
        {% include "partials/header.html" %}
        <br>
        <br>
        <br>
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/partials/footer.html
<style type="text/css">
	#copyright{
		font-family: verdana;
		font-size: 16px;
		text-align: center;
	}
</style>
<hr></hr>
<p id="copyright">&copy; {{author}}</p>

templates/partials/header.html
<!-- Fixed navbar -->
<style type="text/css">
    .bg-navbar{
        background-color: #71b5ff
    }

    .navbar-header .navbar-brand{
        font-weight: bold;
        color: #f9ffed;
        font-family: Montserrat;
        font-size: 24px;
    }
    .navbar-collapse .nav li{
        font-weight: bold;
        color: #f9ffed;
        font-family: Montserrat;
        font-size: 18px;
    }

</style>
<div class="container-fullwidth">
  <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-navbar navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" >LING ON</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a style="color:black" href="/dashboard/"> Dashboard </a> </li>
        <li><a style="color:black" href="/add_friend/"> Add Friend </a></li>
        <li><a style="color:black" href="/status-page/"> Status </a> </li>
        <li><a style="color:black" href="/profile/"> Profile </a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </nav>
</div>